### ISSUE TITLE
 No module named 'downstream_phase_tcn.linear_evaluation'

### ISSUE THREAD

**Issue by YGn31** [CAMMA-public/SelfSupSurg#3]
Greetings. When I try your codes, the part of 
`# 2) TCN fine-tuning        
(selfsupsurg)>cfg=hparams/cholec80/finetuning/cholec_to_cholec/series_01/test/phase_tcn/12.5/1/h002.yaml
(selfsupsurg)>python main_ft_phase_tcn.py -hp $cfg -t test` 
There is an error showing that `ModuleNotFoundError:` No module named 'downstream_phase_tcn.linear_evaluation' 
And after checking the trainers.py line18 `from downstream_phase_tcn.linear_evaluation import FCN`, it seems that there is no such a file (linear_evaluation) in the folder downstream_phase_tcn
Could you please help me to solve this problem?

**Comment by vinkle** [comment]
Hi, added the missing file. Please pull and try again.
