### ISSUE TITLE
How to reproduce the results in Table 6

### ISSUE THREAD

**Issue by yemu1995** [CAMMA-public/SelfSupSurg#4]
Thanks for the paper and codes, I have some questions about the code. I follow the Readme to run the codes, but it only generates the results in Table 4. What should I do if I want to reproduce the results in Table 6?  

Besides
 https://github.com/CAMMA-public/SelfSupSurg/blob/aced56a5b47f6abed36accb3752168c35d76101a/utils/extract_frames_ch80.py#L22
will generate incorrect paths. for example, It changes "video34.mp4" into "video3".

**Comment by vinkle** [comment]
Hi, table 6 uses the relaxed boundary metric to compare with the existing methods for phase recognition. The relaxed boundary based evaluations have issues as outlined in (https://arxiv.org/pdf/2305.13961.pdf). Therefore, we suggest using the F1 metric averaged over videos for appropriate comparisons (as done for other tables). 
Thanks for pointing out an issue in the frame extraction script, we have fixed it.
