### ISSUE TITLE
Few errors in the evaluation code of the experiment listed in Table 6

### ISSUE THREAD

**Issue by yemu1995** [CAMMA-public/SelfSupSurg#5]
Hi, thanks for your code and paper, I may have found some errors in your evaluation code when agg='video_relaxed'.

First the original matlab script 
``` matlab
index = find(prec>100);
prec(index)=100;
index = find(rec>100);
rec(index)=100;
```
They limit the value of precision and recall.

Besides when you compute the 'tp_and_fp'
https://github.com/CAMMA-public/SelfSupSurg/blob/aced56a5b47f6abed36accb3752168c35d76101a/utils/generate_test_results.py#L234-L239
This code will add some 0s into 'tp_and_fp'. For example, if the predictions of frame 5 to frame 8 equals to iPhase, then 

tp_and_fp $=[0,5,0,6,0,7,0,8]$

And if updatedDiff[0] $=0$, the value of tp will increase by 4.

**Comment by vinkle** [comment]
Hi even the Matlab implementation has issues as outlined in (https://arxiv.org/pdf/2305.13961.pdf). We use the relaxed boundary evaluation to compare with the existing phase recognition methods.  However, we suggest using the F1 metric averaged over videos for appropriate comparisons.
